import Head from "next/head";

import { Top } from "./Top";

import type { NextPage } from "next";

export const TopPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Top />
    </>
  );
};
